### ISSUE TITLE
incomplete datasets

### ISSUE THREAD

**Issue by IvanRubtsov** [vertaix/LLM4Mat-Bench#1]
Hello!  I am very interested in your work on benchmarking the prediction of physical and chemical properties with large language models. However, I ran into the following problem: the training sets (https://drive.google.com/drive/folders/1HpGhuNHG4EQCQMZaKPwEQNH9stJKw-ht) contain incomplete datasets (for example, the size of the MP database is about 100k materials, but train.csv contains only about 24k). Is there any mistake here? Is there any way I can download the complete datasets? 
Sincerely, Ivan

**Comment by Andrews2017** [comment]
Dear Ivan,

Thank you for reaching out regarding the LLM4Mat-Bench. We sincerely apologize for the issue with accessing incomplete data. The problem arose from an incomplete download of the dataset from our server to Google Drive.

We have resolved the issue, and you should now have full access to the complete dataset. Please don’t hesitate to let us know if you encounter any further problems or have additional questions.

Best regards,
Andre
